# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
print(np.__version__)
print(np.show_config)

1.21.0
<function show at 0x000001E2F1852E50>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
import numpy as np
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [8]:
import numpy as np
a = np.array([20,30,40,78,89])
print("size of the array:",a.size)
print("memory size of one array:",a.itemsize)


size of the array: 5
memory size of one array: 4


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [15]:
'python-c "import numpy; numpy.info(numpy.add)"'

'python-c "import numpy; numpy.info(numpy.add)"'

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [17]:
b = np.zeros(10)
b[5] = 1
print(b)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [19]:
A = np.arange(10,49)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [21]:
A = np.arange(40)
A = A[::-1]
print(A)

[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [22]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [24]:
a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [26]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [28]:
A=np.random.random((3,3,3))
print(A)

[[[0.76299083 0.39702944 0.23824849]
  [0.52992613 0.73147301 0.72125891]
  [0.6796999  0.28041918 0.89184021]]

 [[0.83839388 0.34848395 0.15347668]
  [0.88157867 0.44628247 0.8604747 ]
  [0.52457799 0.46975219 0.22584428]]

 [[0.32954992 0.75886494 0.94779612]
  [0.680867   0.99197608 0.96206357]
  [0.09891128 0.22772266 0.35999122]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [29]:
B = np.random.random((10,10))
Bmin,Bmax = B.min(), B.max()
print(Bmin,Bmax)

0.014498755393726137 0.9951052484250034


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [32]:
A = np.random.random(30)
M = A.mean()
print(M)

0.4934715988475176


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [33]:
array = np.ones((10,10))
array[1:-1,1:-1] =0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [40]:
a = np.ones((5,5))
a=np.pad(a,pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [42]:
print(0* np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [3]:
import numpy as np
M =np.diag(1+np.arange(4),k=-1)
print(M)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [4]:
D= np.zeros((8,8),dtype=int)
D[1::2,::2] = 1
D[::2,1::2] =1
print(D)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [5]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [10]:
A=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [12]:
B=np.random.random((5,5))
Bmax,Bmin = B.min(),B.max()
B=(B-Bmin)/(Bmax-Bmin)
print(B)

[[ 0.37634656  0.16669393  0.82286862 -0.          0.32369921]
 [ 0.14842799  0.45972089  0.88583231  0.2212285   0.91897018]
 [ 0.49884187  0.74496213  0.99623502  0.8915665   0.64710862]
 [ 1.          0.30656897  0.17775938  0.28632054  0.89476958]
 [ 0.63377373  0.01203875  0.17737202  0.49622341  0.3459707 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [13]:
color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])

C:\Users\anjan\AppData\Local\Temp/ipykernel_11364/2612555575.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [16]:
A = np.dot(np.ones((5,3)),np.ones((3,2)))
print(A)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [17]:
D =np.arange(11)
D[(3<D)&(D<=8)]*=-1
print(D)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [19]:
#Author : Jake VanderPlas

print(sum(range(5),-1))
from numpy import*
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [20]:
Z**Z
2<<Z>>2
Z<-Z
1j*Z
Z/1/1
Z<Z>Z

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [24]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\anjan\AppData\Local\Temp/ipykernel_11364/1356192292.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\anjan\AppData\Local\Temp/ipykernel_11364/1356192292.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [25]:
A= np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(A)),A))

[-8.  3.  9.  5.  1. -7. -3. -5.  8.  5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [40]:
A1 = np.array([0,4,7])
A2 = np.array([0,5,7])
print(np.intersect1d(A1,A2))


[0 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [47]:
defaults = np.seterr(all= "ignore")
A = np.ones(1)/0
_=np.seterr(**defaults)


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [48]:
import numpy as np
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [49]:
yesterday = np.datetime64('today','D')- np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow= np.datetime64('today','D')+np.timedelta64(1,'D')
print("Yesterday:",yesterday)
print("Today:",today)
print("Tomorrow:",tomorrow)

Yesterday: 2021-08-11
Today: 2021-08-12
Tomorrow: 2021-08-13


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [50]:
print("july,2016")
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

july,2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [51]:
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
np.add(A,B, out=B)
np.divide(A,2,out=A)
np.negative(A, out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [56]:
A = np.random.random([0,10,10])
print(A-A%1)
print(np.floor(A))
print(np.ceil(A)-1)
print(A.astype(int))
print(np.trunc(A))

[]
[]
[]
[]
[]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [57]:
A=np.zeros((5,5))
A+=np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [63]:
def generate():
    for x in range(10):
        yield x
        A=np.fromiter(generate(),dtype=float,count=-1)
        print(A)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [64]:
A= np.linspace(0,1,12,endpoint=True)[1:-1]
print(A)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [65]:
A = np.random.random(10)
A.sort()
print(A)

[0.00278169 0.26912672 0.32734457 0.34366388 0.43012868 0.490182
 0.49699658 0.71969278 0.72935893 0.75427983]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [66]:
A=np.arange(10)
np.add.reduce(A)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [68]:
A=np.array([0,5,2])
B=np.array([0,5,2])
#values with tolerance
equal=np.allclose(A,B)
print(equal)
#exact values
equal=np.array_equal(A,B)
print(equal)


True
True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [71]:
A=np.zeros(10)
A.flags.writeable=False
A[0]=1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [72]:
D=np.random.random((10,2))
A,B=D[:,0],D[:,1]
C=np.sqrt(A**2+B**2)
E=np.arctan2(A,B)
print(C)
print(D)

[0.96461456 0.99300935 0.71330523 1.21368885 0.58355484 0.1779005
 0.78969516 0.69385929 1.12667267 0.95118294]
[[0.9012095  0.34395158]
 [0.40859884 0.90504947]
 [0.70464903 0.11078847]
 [0.80521652 0.90811176]
 [0.17718487 0.55600519]
 [0.17567762 0.02803501]
 [0.04132641 0.78861307]
 [0.23382758 0.65327282]
 [0.68067385 0.89781647]
 [0.7156204  0.62660707]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [74]:
A=np.random.random(10)
A[A.argmax()]=0
print(A)

[0.34947107 0.74092205 0.33177464 0.46871199 0.         0.66646685
 0.32039285 0.28955474 0.71348361 0.18697845]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [5]:
import numpy as np
A=np.zeros((10,10),[('x',float),('y',float)])
A['x'],A['y']=np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print(A)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [6]:
for dtype in[np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).max)
    print(np.iinfo(dtype).min)
for dtype in[np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)  
    print(np.finfo(dtype).eps)  

127
-128
2147483647
-2147483648
9223372036854775807
-9223372036854775808
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [15]:
np.set_printoptions(threshold=5)
S=np.zeros((25,25))
print(S)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [17]:
x=np.arange(100)
a=np.random.uniform(0,100)
print(a)
index=(np.abs(x-a)).argmin()
print(x[index])

38.996040722064606
39


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [18]:
D=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
print(D)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\anjan\AppData\Local\Temp/ipykernel_3848/675014273.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  D=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [20]:
Z= np.random.random((10,2))
X,Y=np.atleast_2d(Z[:,0],Z[:,1])
A=np.sqrt((X-X.T)**2+(Y-Y.T)**2)
print(A)


[[0.         0.21313408 0.30497242 ... 0.77356517 0.26993465 0.71665194]
 [0.21313408 0.         0.1377626  ... 0.94442334 0.46627839 0.68388515]
 [0.30497242 0.1377626  0.         ... 0.94605459 0.57375085 0.56742152]
 ...
 [0.77356517 0.94442334 0.94605459 ... 0.         0.73502418 0.81513094]
 [0.26993465 0.46627839 0.57375085 ... 0.73502418 0.         0.93465157]
 [0.71665194 0.68388515 0.56742152 ... 0.81513094 0.93465157 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [22]:
A=np.arange(10,dtype=np.int32)
A=A.astype(np.float32,copy=False)
print(A)

[0. 1. 2. ... 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [26]:
from io import StringIO
s=StringIO("""1,2,3,4,5\n 
6,,,7,8\n
,,9,10,11\n""")
A=np.genfromtxt(s,delimiter=",",dtype=int)
print(A)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [28]:
Z=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):
    print(index,value)
for index in np.ndindex(Z.shape):
    print(index,Z[index])    

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [32]:
X,Y =np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D=np.sqrt(X*Y+Y*Y)
sigma,mu=1.0,0.0
G=np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)

[[0.36787944 0.41111229 0.45942582 ... 0.8007374  0.89483932 1.        ]
 [0.50089538 0.54610814 0.59540197 ... 0.91720915 1.                nan]
 [0.64914526 0.69047855 0.73444367 ... 1.                nan        nan]
 ...
 [       nan        nan        nan ... 0.73444367 0.69047855 0.64914526]
 [       nan        nan 0.91720915 ... 0.59540197 0.54610814 0.50089538]
 [1.         0.89483932 0.8007374  ... 0.45942582 0.41111229 0.36787944]]


C:\Users\anjan\AppData\Local\Temp/ipykernel_3848/4289361744.py:2: RuntimeWarning: invalid value encountered in sqrt
  D=np.sqrt(X*Y+Y*Y)


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [39]:
n=10
p=3
Z=np.zeros((n,n))
Z=np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
print(Z)

None


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [40]:
X=np.random.rand(5,10)
Y=X-X.mean(axis=1,keepdims=True)
print(Y)

[[ 0.25046399 -0.1965151   0.29355344 ... -0.20250198 -0.36155687
   0.01470441]
 [-0.25454521  0.12325063  0.29417228 ...  0.38327784 -0.33520808
  -0.34928949]
 [ 0.1023491  -0.154415    0.43327202 ... -0.35930112  0.33716453
  -0.36848803]
 [-0.01175711  0.18659316 -0.28356478 ... -0.42279432 -0.21103663
   0.01187706]
 [ 0.26951384  0.41277196 -0.42788973 ... -0.3159756   0.13293846
   0.22157344]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [43]:
A=np.random.randint(1,10,(3,3))
print(A)
print(A[A[:,1].argsort()])

[[6 7 6]
 [8 4 7]
 [8 4 6]]
[[8 4 7]
 [8 4 6]
 [6 7 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [51]:
A=np.array([2,4,5])
print(A)
print((~A.any(axis=0)).any())

[2 4 5]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [53]:
A=np.random.uniform(0,1,10)
a=0.5
m=A.flat[np.abs(A-a).argmin()]
print(m)

0.5089615781551455


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [56]:
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
it=np.nditer([A,B,None])
for x,y,z in it:z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [72]:
class NamedArray(np.ndarray):
 def__new__(class,array,name="no name"):
obj=np.asarray(array).view(class)
obj.name=name
   return obj
def__array__finalize__(self,obj):
if obj is None:
  return 
self.info=getattr(obj,'name',"no name")
Z=NamedArray(np.arange(10),"range_10")
print(Z.name)

SyntaxError: invalid syntax (Temp/ipykernel_3848/3765404518.py, line 2)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [75]:
Z=np.ones(10)
I=np.random.randint(0,len(Z),20)
Z+=np.bincount(I,minlength=len(Z))
print(Z)

[3. 3. 1. ... 3. 3. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [77]:
X=[1,2,3,4,5,6]
I=[1,3,9,3,4,1]
F=np.bincount(I,X)
print(F)

[0. 7. 0. ... 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [80]:
w,h=16,16
I=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F=I[...,0]*256*256+I[...,1]*256+I[...,2]
n=len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [91]:
A=np.random.randint(0,10,(3,4,3,4))
sum=A.sum(axis=(-2,-1))
print(sum)
sum=A.reshape(A.shape[:-2]+(-1,)).sum(axis=-1)
print(sum)

[[54 58 62 43]
 [43 67 45 65]
 [66 68 63 49]]
[[54 58 62 43]
 [43 67 45 65]
 [66 68 63 49]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [92]:
D=np.random.uniform(0,1,100)
S=np.random.randint(0,10,100)
D_sums=np.bincount(S,weights=D)
D_counts =np.bincount(S)
D_means=D_sums/D_counts
print(D_means)

[0.38535256 0.67308989 0.5522363  ... 0.78604631 0.57443368 0.59032724]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [97]:
A=np.random.rand(1000,200)
B=np.random.rand(200,200)
print(np.diag(np.dot(A,B)))



[45.7604496  52.93451659 48.04232393 ... 50.78942626 49.48072901
 52.96107105]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [2]:
import numpy as np
A=np.array([1,2,3,4,5])
nz=3
A0=np.zeros(len(A)+(len(A)-1)*(nz))
A0[::nz+1]=A
print(A0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [3]:
A=np.ones((5,5,3))
B=2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [8]:
A=np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [26]:
faces=np.random.randint(0,100,(10,3))
F=np.roll(faces.repeat(2,axis=1),-1,axis=1)
F=F.reshape(len(F)*3,2)
F=np.sort(F,axis=1)
G=F.view(dtype=[('p0',F.dtype),('p1',F.dtype)])
G=np.unique(G)
print(G)

[( 5, 50) ( 5, 65) ( 7, 75) ( 7, 83) ( 9, 37) ( 9, 95) (11, 31) (11, 74)
 (12, 24) (12, 58) (17, 28) (17, 69) (18, 39) (18, 68) (24, 32) (24, 58)
 (24, 83) (26, 49) (26, 98) (28, 69) (31, 74) (32, 83) (37, 95) (39, 68)
 (49, 98) (50, 52) (50, 65) (50, 89) (52, 89) (75, 83)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [31]:
D=np.bincount([1,1,2,3,4,4,6])
A=np.repeat(np.arange(len(D)),D)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [32]:
def moving_average(a,n=3):
    ret=np.cumsum(a, dtype=float)
    ret[n:]=ret[n:]-ret[:-n]
    return ret[n-1:]/n 
Z=np.arange(20)
print(moving_average(Z, n=3))    

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [36]:
def rolling(a,window):
    shape =(a.size - window +1,window)
    strides = (a.itemsize,a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z=rolling(np.arange(10),3)
print(Z)    

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [44]:
Z= np.random.randint(0,2,100)
print("original:")
print(Z)
print("Negating a boolean:")
print(np.logical_not(Z,out=Z))

Z=np.random.uniform(-1.0,1.0,10)
print("original:")
print(Z)
print("Change the sign of float inplace:")
print(np.negative(Z,out=Z))

original:
[1 0 1 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0
 0 1 1 0 0 0 0 0 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0
 0 0 0 1 1 0 1 1 0 1 1 0 0 1 1 1 0 1 1 0 0 1 0 1 0 1]
Negating a boolean:
[0 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 0 1
 1 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 1 1
 1 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 0 1 1 0 1 0 1 0]
original:
[ 0.95751796 -0.08846633 -0.05565634 -0.36976287  0.21189027 -0.51241106
 -0.49867193 -0.8579132   0.99021199  0.60063761]
Change the sign of float inplace:
[-0.95751796  0.08846633  0.05565634  0.36976287 -0.21189027  0.51241106
  0.49867193  0.8579132  -0.99021199 -0.60063761]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [57]:
def distance(P0,P1,p):
    T=P1-P0
    L=(T**2).sum(axis=1)
    U=-((P0[:,0]-p[...,0])*T[:,0]+(P0[:,1]-p[...,1])*T[:,1]/L)
    U=U.reshape(len(U),1)
    D=P0+U*T-p
    return np.sqrt((D**2).sum(axis=1))
P0 =np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(1,2)) 
print(distance(P0,P1,p)) 

[  25.76887176  374.92001205  136.84638867  240.62802727   46.21149303
  192.45074267 1001.84568926   54.42935533  251.34828804  163.25449587]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [61]:
 def distance(P0,P1,P):
    T=P1-P0
    L=(T**2).sum(axis=1)
    U=-((P0[:,0]-P[...,0])*T[:,0]+(P0[:,1]-P[...,1])*T[:,1]/L)
    U=U.reshape(len(U),1)
    D=P0+U*T-P
    return np.sqrt((D**2).sum(axis=1))
P0 =np.random.uniform(-10,10,(5,2))
P1=np.random.uniform(-10,10,(5,2))
P=np.random.uniform(-10,10,(5,2))    
print(np.array([distance(P0,P1,P_i)for P_i in P]))

[[1025.11763104 1025.93619783  555.83609683   43.98106752 2172.95103093]
 [ 834.23920473 1585.29408032  445.55324239   35.62888257 1817.1448711 ]
 [1355.29212867   58.43399277  746.66063622   57.95517513 2788.19347393]
 [ 535.71643613 2460.10654356  273.06184089   22.91919565 1260.82149029]
 [ 106.43820585 4341.71910605   98.04318378    4.76073636   64.13334305]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [72]:
Z=np.random.randint(0,10,(10,10))
shape=(5,5)
fill=0
position=(1,1)
R=np.ones(shape,dtype=Z.dtype)*fill 
P=np.array(list(position)).astype(int)
Rs=np.array(list(R.shape)).astype(int)
Zs=np.array(list(Z.shape)).astype(int)

R_start=np.zeros((len(shape),)).astype(int)
R_stop=np.array(list(shape)).astype(int)
Z_start= (P-Rs//2)
Z_stop=(P+Rs//2)+Rs%2

R_start=(R_start-np.minimum(Z_start,0)).tolist()
Z_start=(np.maximum(Z_start,0)).tolist()
R_stop=np.maximum(R_start,(R_stop-np.maximum(Z_stop-Zs,0))).tolist()
Z_stop=(np.minimum(Z_stop,Zs)).tolist()

r=[slice(start,stop) for start,stop in zip(R_start,R_stop)]
z=[slice(start,stop)for start,stop in zip(Z_start,Z_stop)]
R[(r)] = Z[(z)]
print(Z)
print(R)


[[5 2 3 7 4 3 9 7 5 0]
 [5 2 3 7 2 4 6 4 2 4]
 [6 5 7 0 6 5 0 6 6 1]
 [0 8 3 4 1 0 1 0 7 9]
 [3 6 0 0 9 9 0 9 7 3]
 [4 8 6 2 2 5 1 1 1 3]
 [4 1 2 3 4 9 8 2 1 2]
 [5 8 3 9 0 9 1 9 6 8]
 [3 6 1 3 8 6 5 4 1 9]
 [3 9 2 4 3 1 1 9 5 2]]
[[0 0 0 0 0]
 [0 5 2 3 7]
 [0 5 2 3 7]
 [0 6 5 7 0]
 [0 0 8 3 4]]


C:\Users\anjan\AppData\Local\Temp/ipykernel_13812/2162615439.py:22: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[(r)] = Z[(z)]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [76]:
Z=np.arange(1,15,dtype=int)

def rolling(a,window):
    shape=(a.size-window+1,window)
    strides =(a.itemsize,a.itemsize)
    return np.lib.stride_tricks.as_strided(a,shape=shape,strides=strides)

R= rolling(Z,4)
print('original')
print(Z)
print('after strides:')
print(R)

original
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
after strides:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [77]:
Z = np.random.uniform(0,1,(10,10))
U,S,V = np.linalg.svd(Z)
rank = np.sum(S>1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [78]:
Z=np.random.randint(0,10,50)
print(Z)
print('rank:',np.bincount(Z).argmax())

[5 8 8 8 1 6 0 0 1 1 4 2 0 0 4 5 9 9 8 5 1 6 0 5 8 4 4 0 3 6 0 8 3 5 4 7 8
 8 5 9 0 6 9 7 7 8 7 2 8 6]
rank: 8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [79]:
Z=np.random.randint(0,5,(6,6))
n=3
i=1+(Z.shape[0]-3)
j=1+(Z.shape[1]-3)
C=np.lib.stride_tricks.as_strided(Z,shape=(i,j,n,n),strides=Z.strides+Z.strides)
print(C)

[[[[1 1 2]
   [2 1 2]
   [3 3 2]]

  [[1 2 1]
   [1 2 2]
   [3 2 4]]

  [[2 1 1]
   [2 2 1]
   [2 4 2]]

  [[1 1 0]
   [2 1 4]
   [4 2 4]]]


 [[[2 1 2]
   [3 3 2]
   [2 0 1]]

  [[1 2 2]
   [3 2 4]
   [0 1 4]]

  [[2 2 1]
   [2 4 2]
   [1 4 4]]

  [[2 1 4]
   [4 2 4]
   [4 4 2]]]


 [[[3 3 2]
   [2 0 1]
   [4 1 0]]

  [[3 2 4]
   [0 1 4]
   [1 0 1]]

  [[2 4 2]
   [1 4 4]
   [0 1 0]]

  [[4 2 4]
   [4 4 2]
   [1 0 2]]]


 [[[2 0 1]
   [4 1 0]
   [3 2 0]]

  [[0 1 4]
   [1 0 1]
   [2 0 1]]

  [[1 4 4]
   [0 1 0]
   [0 1 1]]

  [[4 4 2]
   [1 0 2]
   [1 1 1]]]]


#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [104]:
class Symetric(np.ndarray):
  def __setitem__(self,index, value):         
     i,j=index
super(Symetric,self).__setitem__((i,j),value)
super(Symetric,self).__setitem__((j,i),value)
def symetric(Z):
    return np.asarray(Z+Z.T- np.diag(Z.diagonal())).view(Symetric)
S=symetric(np.random.randint(0,10,(5,5))) 
S[2,3]=42
print(S)


NameError: name 'self' is not defined

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [105]:
p,n = 10,20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
S=np.tensordot(M,V,axes=[[0,2],[0,1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [106]:
Z=np.ones((16,16))
k=4
S=np.add.reduceat(np.add.reduceat(Z,np.arange(0,Z.shape[0],k),axis=0),np.arange(0,Z.shape[1],k),axis=1)
print("input array")
print(Z)
print("block sum")
print(S)

input array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [108]:
def iterate(A):
    N=(A[0:-2,0:-2]+A[0:-2,1:-1]+A[0:-2,2:]+A[1:-1,0:-2]+A[1:-1,2]+A[2:,0:-2]+A[2:,1:-1]+A[2:,2:])
    birth=(N==3)&(A[1:-1,1:-1]==0)
    survive=((N==2)|(N==3))&(A[1:-1,1:-1]==1)
    A[...]=0
    A[1:-1,1:-1][birth|survive]=1
    return A
A=np.random.randint(0,2,(50,50))
for i in range(100):A=iterate(A)    

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [111]:
B=np.arange(10000)
np.random.shuffle(B)
n=5
#method 1
print(B[np.argsort(B)[-n:1]])
#method 2
print(B[np.argpartition(-B,n)[:n]])

[]
[9997 9999 9998 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [128]:
def cartesian(arrays):
    arrays=[np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix=np.indices(shape,dtype=int) 
    ix=ix.reshape(len(arrays),-1).T

    for n,arr in enumerate(arrays):
        ix[:, n]=arrays[n][ix[:,n]]
        return ix
print(cartesian(([1,2,3], [4,5], [6,7]))) 


[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]
 [3 0 0]
 [3 0 1]
 [3 1 0]
 [3 1 1]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [130]:
A=np.array([("hello",2.5,3),("World",3.6,2)])
R=np.core.records.fromarrays(A.T,names='col1,col2,col3',formats="S8,f8,i8")

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [138]:
X=np.random.rand(7)
%timeit np.power(X,3)
%timeit X*X*X
%timeit np.einsum('i,i,i->i',X,X,X)


2.96 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.72 µs ± 69.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
5.36 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [141]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[...,np.newaxis,np.newaxis]==B)
rows=(C.sum(axis=(1,2,3))>=B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [148]:
Z=np.random.randint(0,5,(10,3))
E=np.logical_and.reduce(Z[:,1:]==Z[:,:-1], axis=1)
U=Z[~E]
print(Z)
print(U)

[[1 4 3]
 [1 3 1]
 [0 1 4]
 [0 2 1]
 [0 1 0]
 [1 4 0]
 [0 1 3]
 [4 1 1]
 [0 3 3]
 [4 2 1]]
[[1 4 3]
 [1 3 1]
 [0 1 4]
 [0 2 1]
 [0 1 0]
 [1 4 0]
 [0 1 3]
 [4 1 1]
 [0 3 3]
 [4 2 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [149]:
I=np.array([0,1,2,3,15,16,32,64,128])
B=((I.reshape(-1,1)&(2**np.arange(8)))!=0).astype(int) 
print(B[:,::-1])
I=np.array([0,1,2,3,15,16,32,64,128],dtype=np.uint8)
print(np.unpackbits(I[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [151]:
Z=np.random.randint(0,2,(6,3))
T=np.ascontiguousarray(Z).view(np.dtype((np.void,Z.dtype.itemsize*Z.shape[1])))
_, idx=np.unique(T,return_index=True)
uZ=Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [156]:
A=np.arange(3)
B=np.arange(12).reshape(3,4)
print(A)
#np.einsum('ii->',A)  #np.sum(A)
#np.einsum('i,i->i',A,B)#A*B
#np.einsum('i,i',A,B) #np.inner(A,B)
#np.einsum('...i,j',A,B)#np.outer(A,B)

[0 1 2]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [158]:
phi =np.arange(0, 10*np.pi, 0.1)
a=1
x =a*phi*np.cos(phi)
y= a*phi*np.sin(phi)

dr=(np.diff(x)**2 + np.diff(y)**2)**.5
r=np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(),200)
x_int = np.interp(r_int,r,x)
y_int = np.interp(r_int,r,y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [165]:
X=np.asarray([[1.0,0.0,3.0,8.0],[2.0,0.0,1.0,1.0],[1.5,2.5,1.0,0.0]])
n=4
M=np.logical_and.reduce(np.mod(X,1)==0,axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [166]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size,(N, X.size))
means = X[idx].mean(axis=1)
confint=np.percentile(means,[2.5, 97.5])
print(confint)

[-0.16608661  0.22833622]
